import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||3000);
const products=[
{id:'1001',title:'Комплект постельного белья',category:'Текстиль',price:1250,wholesale:1080,moq:10,seller:'Дом Текстиля',pavilion:'B-214',badge:'Новинка',image:'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=900&q=80'},
{id:'1002',title:'Набор полотенец 6 шт.',category:'Текстиль',price:790,wholesale:640,moq:12,seller:'Cotton Market',pavilion:'C-118',badge:'Опт',image:'https://images.unsplash.com/photo-1600369671236-e74521d4b6ad?auto=format&fit=crop&w=900&q=80'},
{id:'1003',title:'Мягкая игрушка',category:'Игрушки',price:550,wholesale:420,moq:20,seller:'Toy City',pavilion:'E-307',badge:'Хит',image:'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=900&q=80'},
{id:'1004',title:'Набор кухонной посуды',category:'Посуда',price:2490,wholesale:2150,moq:6,seller:'Kitchen Pro',pavilion:'A-422',badge:'Акция',image:'https://images.unsplash.com/photo-1584990347449-ae0fa1a6c611?auto=format&fit=crop&w=900&q=80'},
{id:'1005',title:'Плед 200×220 см',category:'Текстиль',price:990,wholesale:810,moq:10,seller:'Comfort Home',pavilion:'D-145',badge:'Новинка',image:'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=900&q=80'},
{id:'1006',title:'Органайзер для дома',category:'Товары для дома',price:390,wholesale:295,moq:30,seller:'Home Box',pavilion:'F-102',badge:'Опт',image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=80'}
];

const appHtml=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08101c"><title>UVMALL — Южные Ворота онлайн</title><script src="https://telegram.org/js/telegram-web-app.js"><\/script><style>
*{box-sizing:border-box}body{margin:0;background:#08101c;color:#f6f8fc;font-family:Inter,system-ui,-apple-system,sans-serif}.app{max-width:720px;margin:auto;padding:16px 14px 92px}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:24px;font-weight:900}.sub{color:#9cabbe;font-size:12px}.hero{margin:18px 0;background:linear-gradient(135deg,#16325a,#30216a);padding:20px;border-radius:22px;border:1px solid #355382}.hero h1{font-size:25px;margin:0 0 8px}.hero p{margin:0;color:#cbd5e5}.search{width:100%;background:#101b2e;color:#fff;border:1px solid #263652;border-radius:15px;padding:14px;margin-bottom:14px}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:18px}.quick button,.chip{background:#111d31;color:#fff;border:1px solid #273850;border-radius:14px;padding:11px}.chips{display:flex;overflow:auto;gap:8px;margin:8px 0 16px}.chip{white-space:nowrap}.chip.active{background:#315ea6}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.card{background:#111d30;border:1px solid #24344e;border-radius:18px;overflow:hidden}.pic{aspect-ratio:1/1;position:relative;background:#1a263b}.pic img{width:100%;height:100%;object-fit:cover}.badge{position:absolute;left:7px;top:7px;background:#07101ddd;padding:5px 8px;border-radius:99px;font-size:10px}.body{padding:10px}.title{font-size:13px;font-weight:800;min-height:34px}.price{font-size:17px;font-weight:900;margin-top:7px}.wh{font-size:11px;color:#36d39b;margin-top:3px}.seller{font-size:11px;color:#99a8bb;margin-top:7px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bottom{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:min(720px,100%);display:grid;grid-template-columns:repeat(4,1fr);background:#09121ef5;border-top:1px solid #263652;padding:9px 8px calc(9px + env(safe-area-inset-bottom))}.bottom button{border:0;background:none;color:#b8c3d2}.modal{display:none;position:fixed;inset:0;background:#040812dd;align-items:flex-end;z-index:10}.sheet{width:min(720px,100%);margin:auto;background:#101b2d;border-radius:24px 24px 0 0;padding:16px 16px 28px;max-height:88vh;overflow:auto}.sheet img{width:100%;border-radius:18px;aspect-ratio:16/10;object-fit:cover}.cta{width:100%;border:0;border-radius:14px;padding:14px;background:linear-gradient(135deg,#559cff,#7547e8);color:#fff;font-weight:900}.muted{color:#9dabbc}.empty{text-align:center;color:#93a2b5;grid-column:1/-1;padding:30px}@media(min-width:650px){.grid{grid-template-columns:repeat(3,1fr)}}
</style></head><body><main class="app"><div class="top"><div><div class="brand">UVMALL</div><div class="sub">Южные Ворота онлайн</div></div><button onclick="location.href='/setup'" style="background:#111d31;border:1px solid #263652;color:white;border-radius:12px;padding:10px">⚙</button></div><section class="hero"><h1>Найдите товар быстрее</h1><p>Каталог продавцов, оптовые цены и павильоны ТК «Южные Ворота» прямо в Telegram.</p></section><input id="search" class="search" placeholder="Товар, продавец или павильон…"><div class="quick"><button onclick="showNew()">✦ Новинки</button><button onclick="showDeals()">🔥 Акции</button><button onclick="showFav()">♡ Избранное</button></div><div id="chips" class="chips"></div><div id="grid" class="grid"></div></main><nav class="bottom"><button onclick="reset()">⌂<br>Главная</button><button onclick="search.focus()">⌕<br>Поиск</button><button onclick="showFav()">♡<br>Избранное</button><button onclick="openWeb()">↗<br>UVMALL.ru</button></nav><div id="modal" class="modal" onclick="if(event.target===this)closeModal()"><div id="sheet" class="sheet"></div></div><script>
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}let items=[],cat='',fav=new Set(JSON.parse(localStorage.getItem('uvmall:fav')||'[]'));const rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
async function load(){try{const r=await fetch('/api/products');const j=await r.json();items=j.items||[]}catch{}drawChips();apply()}function drawChips(){const cats=['Все',...new Set(items.map(x=>x.category))];chips.innerHTML=cats.map(x=>'<button class="chip '+((x==='Все'&&!cat)||x===cat?'active':'')+'" onclick="setCat(\''+(x==='Все'?'':x)+'\')">'+x+'</button>').join('')}function setCat(x){cat=x;drawChips();apply()}function apply(){const q=search.value.trim().toLowerCase();render(items.filter(x=>(!cat||x.category===cat)&&(!q||(x.title+' '+x.seller+' '+x.pavilion).toLowerCase().includes(q))))}function render(a){grid.innerHTML=a.length?a.map(p=>'<article class="card" onclick="openP(\''+p.id+'\')"><div class="pic"><img src="'+p.image+'"><span class="badge">'+p.badge+'</span></div><div class="body"><div class="title">'+p.title+'</div><div class="price">'+rub(p.price)+'</div><div class="wh">Опт '+rub(p.wholesale)+' от '+p.moq+' шт.</div><div class="seller">'+p.seller+' · '+p.pavilion+'</div></div></article>').join(''):'<div class="empty">Ничего не найдено</div>'}function openP(id){const p=items.find(x=>x.id===id);if(!p)return;sheet.innerHTML='<button onclick="closeModal()" style="float:right">Закрыть</button><img src="'+p.image+'"><h2>'+p.title+'</h2><div class="price">'+rub(p.price)+'</div><div class="wh">Оптовая цена '+rub(p.wholesale)+' от '+p.moq+' шт.</div><p class="muted">Продавец: '+p.seller+'<br>Павильон: '+p.pavilion+'</p><button class="cta" onclick="openProduct(\''+p.id+'\')">🛍 Открыть на UVMALL.ru</button>';modal.style.display='flex';tg?.BackButton.show();tg?.BackButton.onClick(closeModal)}function closeModal(){modal.style.display='none';tg?.BackButton.hide()}function toggle(id){fav.has(id)?fav.delete(id):fav.add(id);localStorage.setItem('uvmall:fav',JSON.stringify([...fav]))}function showFav(){render(items.filter(x=>fav.has(x.id)))}function showNew(){render(items.filter(x=>x.badge==='Новинка'))}function showDeals(){render(items.filter(x=>x.badge==='Акция'))}function reset(){cat='';search.value='';drawChips();render(items)}function openWeb(){const u='https://uvmall.ru';tg?.openLink?tg.openLink(u):window.open(u,'_blank')}function openProduct(id){const u='https://uvmall.ru/product/'+encodeURIComponent(id);tg?.openLink?tg.openLink(u):window.open(u,'_blank')}search.addEventListener('input',apply);load();
<\/script></body></html>`;

const setupHtml=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UVMALL — настройка</title><style>body{margin:0;background:#09111f;color:#eef3fa;font-family:system-ui;padding:24px}main{max-width:760px;margin:auto}.box{background:#121d30;border:1px solid #263650;border-radius:18px;padding:18px;margin:12px 0}code{background:#07101e;padding:3px 7px;border-radius:7px;word-break:break-all}.muted{color:#a4b1c4}a{color:#78adff}</style></head><body><main><h1>UVMALL Mini App</h1><p class="muted">Канал @uvmall · Бот @UVMALL_bot</p><div class="box"><b>1. Railway</b><p>Приложение должно быть опубликовано по HTTPS. Проверьте <code>/api/health</code>.</p></div><div class="box"><b>2. BotFather</b><p><code>/mybots → @UVMALL_bot → Bot Settings → Menu Button</code><br>Текст: <code>🛍 Открыть UVMALL</code><br>URL: публичный адрес Railway.</p></div><div class="box"><b>3. Канал</b><p>Добавьте @UVMALL_bot администратором @uvmall с правом публикации.</p></div><div class="box"><b>4. Переменные Railway</b><p><code>TELEGRAM_BOT_TOKEN</code><br><code>TELEGRAM_CHANNEL_ID=@uvmall</code><br><code>UVMALL_AUTOPOST_SECRET</code></p></div><p><a href="/">← Открыть Mini App</a></p></main></body></html>`;

function sendJson(res,status,obj){const s=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(s)}
async function readJson(req){let b='';for await(const c of req){b+=c;if(b.length>1e6)throw Error()}return b?JSON.parse(b):{}}
function safe(a,b){const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function clean(v=''){return String(v).replace(/[<>]/g,'').trim()}

const server=http.createServer(async(req,res)=>{
 const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);
 if(u.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(appHtml)}
 if(u.pathname==='/setup'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(setupHtml)}
 if(u.pathname==='/api/health')return sendJson(res,200,{ok:true,service:'UVMALL Telegram Mini App',platform:'railway',channel:process.env.TELEGRAM_CHANNEL_ID||'@uvmall',botConfigured:Boolean(process.env.TELEGRAM_BOT_TOKEN),autopostSecretConfigured:Boolean(process.env.UVMALL_AUTOPOST_SECRET),timestamp:new Date().toISOString()});
 if(u.pathname==='/api/products'&&req.method==='GET'){const q=(u.searchParams.get('q')||'').toLowerCase(),c=(u.searchParams.get('category')||'').toLowerCase();const a=products.filter(p=>(!q||(p.title+' '+p.seller+' '+p.pavilion).toLowerCase().includes(q))&&(!c||p.category.toLowerCase()===c));return sendJson(res,200,{items:a,total:a.length,source:'demo-adapter'})}
 if(u.pathname==='/api/telegram-auth'){
  if(req.method!=='POST')return sendJson(res,405,{ok:false,error:'method_not_allowed'});const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)return sendJson(res,503,{ok:false,error:'telegram_bot_not_configured'});let body;try{body=await readJson(req)}catch{return sendJson(res,400,{ok:false,error:'invalid_json'})}const initData=String(body.initData||'');if(!initData)return sendJson(res,400,{ok:false,error:'init_data_required'});const p=new URLSearchParams(initData),hash=p.get('hash');p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');const secret=crypto.createHmac('sha256','WebAppData').update(token).digest();const calc=crypto.createHmac('sha256',secret).update(check).digest('hex');const d=Number(p.get('auth_date')||0),fresh=d&&(Math.floor(Date.now()/1000)-d)<86400;if(!safe(calc,hash)||!fresh)return sendJson(res,401,{ok:false,error:'invalid_init_data'});let user=null;try{user=JSON.parse(p.get('user')||'null')}catch{}return sendJson(res,200,{ok:true,user})
 }
 if(u.pathname==='/api/autopost'){
  if(req.method!=='POST')return sendJson(res,405,{ok:false,error:'method_not_allowed'});const expected=process.env.UVMALL_AUTOPOST_SECRET,provided=req.headers['x-uvmall-secret'];if(!expected||provided!==expected)return sendJson(res,401,{ok:false,error:'unauthorized'});const token=process.env.TELEGRAM_BOT_TOKEN,chat=process.env.TELEGRAM_CHANNEL_ID||'@uvmall';if(!token)return sendJson(res,503,{ok:false,error:'telegram_bot_not_configured'});let p;try{p=await readJson(req)}catch{return sendJson(res,400,{ok:false,error:'invalid_json'})}const title=clean(p.title||'Новый товар'),seller=clean(p.seller||'Продавец UVMALL'),pavilion=clean(p.pavilion||'—'),price=Number(p.price||0),wh=Number(p.wholesale||0),moq=Number(p.moq||0),url=/^https:\/\//.test(String(p.url||''))?String(p.url):'https://uvmall.ru/product/'+encodeURIComponent(p.id||'');const lines=['🆕 <b>Новинка на UVMALL</b>','',`<b>${title}</b>`,price?`💰 Цена: ${price.toLocaleString('ru-RU')} ₽`:'',wh?`📦 Опт: ${wh.toLocaleString('ru-RU')} ₽${moq?' от '+moq+' шт.':''}`:'',`🏪 ${seller}`,`📍 Павильон: ${pavilion}`].filter(Boolean);const payload={chat_id:chat,parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'🛍 Посмотреть на UVMALL',url}]]}};let method='sendMessage';if(/^https:\/\//.test(String(p.image||''))){method='sendPhoto';payload.photo=String(p.image);payload.caption=lines.join('\n')}else payload.text=lines.join('\n');try{const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)return sendJson(res,502,{ok:false,error:'telegram_error',details:j});return sendJson(res,200,{ok:true,messageId:j.result?.message_id,chatId:chat})}catch{return sendJson(res,502,{ok:false,error:'telegram_unreachable'})}
 }
 return sendJson(res,404,{ok:false,error:'not_found'})
});
server.listen(PORT,'0.0.0.0',()=>console.log('UVMALL Mini App listening on '+PORT));
