(() => {
  const H=window.H,D=H.D,E=H.esc,B=H.badge,S=H.sourcesHtml;
  H.pages=H.pages||{};

  H.pages.home=()=>{
    const pub=H.records().filter(x=>!x.private), verified=pub.filter(x=>x.status==='documented').length;
    return '<section class="hero"><div class="hero-copy"><div class="kicker">ЕДИНЫЙ ЦИФРОВОЙ АРХИВ</div><h1>Память не должна<br>жить по отдельности.</h1><p>Один сайт для истории горских евреев, Красной Слободы, джуури, семей, документов, кладбищ, культуры и устной памяти.</p><div class="hero-actions"><a class="btn primary" href="#/red-village">Исследовать Красную Слободу</a><a class="btn secondary" href="#/ask">Спросить архив</a></div><div class="hero-note"><span></span>Все разделы работают внутри этого сайта. Lovable больше не открывается.</div></div><div class="graph-visual"><svg viewBox="0 0 620 520"><g class="links"><line x1="310" y1="260" x2="310" y2="70"/><line x1="310" y1="260" x2="520" y2="160"/><line x1="310" y1="260" x2="520" y2="370"/><line x1="310" y1="260" x2="310" y2="455"/><line x1="310" y1="260" x2="100" y2="370"/><line x1="310" y1="260" x2="100" y2="160"/></g><g class="g-node center"><circle cx="310" cy="260" r="73"/><text x="310" y="254">Нити</text><text x="310" y="280">Памяти</text></g><g class="g-node"><circle cx="310" cy="70" r="52"/><text x="310" y="75">Джуури</text></g><g class="g-node"><circle cx="520" cy="160" r="52"/><text x="520" y="165">Архив</text></g><g class="g-node"><circle cx="520" cy="370" r="52"/><text x="520" y="375">Семьи</text></g><g class="g-node"><circle cx="310" cy="455" r="52"/><text x="310" y="460">Память</text></g><g class="g-node"><circle cx="100" cy="370" r="52"/><text x="100" y="375">Голоса</text></g><g class="g-node"><circle cx="100" cy="160" r="52"/><text x="100" y="165">Слобода</text></g></svg></div></section>'+
    '<section class="stats-row">'+H.stat('публичных записей',pub.length,'реальные + явно помеченные демо')+H.stat('подтверждённых единиц',verified,'только записи с источником')+H.stat('слов джуури',D.juhuri.length,'в текущем проверенном корпусе')+H.stat('источников',D.sources.length,'библиография и публичные материалы')+'</section>'+

    '<section class="section-block two-col"><div class="panel"><div class="kicker">КРАСНАЯ СЛОБОДА</div><h2>Цифровой двойник</h2><p>Места, дома, синагоги, музей, кладбище и временные слои объединяются с семейными и архивными данными.</p><a class="text-link" href="#/red-village">Открыть карту и хронологию →</a></div><div class="panel dark-panel"><div class="kicker">ДЖУУРИ</div><h2>Язык как живой архив</h2><p>Проверенные словарные статьи, диалектные пометы, источники и учебные карточки — без генерации непроверенных форм.</p><a class="text-link" href="#/juhuri">Открыть языковой центр →</a></div></section>';
  };

  H.placeCard=p=>'<article class="record-card" data-year="'+(p.yearFrom||'')+'"><div class="record-top"><span class="type">'+E(p.type)+'</span>'+B(p.status)+'</div><h3>'+E(p.title)+'</h3>'+(p.alt?'<div class="alt">'+E(p.alt)+'</div>':'')+'<p>'+E(p.summary)+'</p><div class="meta">'+E(p.address||'')+(p.yearFrom?' · с '+E(p.yearFrom):'')+'</div><details><summary>История и источники</summary><p>'+E(p.history||'')+'</p>'+S(p.sources)+'</details></article>';

  H.mapSvg=()=>{
    const pts=D.places.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));
    const minLat=Math.min(...pts.map(p=>p.lat)),maxLat=Math.max(...pts.map(p=>p.lat)),minLng=Math.min(...pts.map(p=>p.lng)),maxLng=Math.max(...pts.map(p=>p.lng));
    const pos=p=>({x:70+((p.lng-minLng)/(maxLng-minLng||1))*760,y:420-((p.lat-minLat)/(maxLat-minLat||1))*320});
    return '<svg class="village-map" viewBox="0 0 900 500"><defs><pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M50 0H0V50" fill="none" stroke="currentColor" opacity=".08"/></pattern></defs><rect width="900" height="500" fill="url(#grid)"/><path d="M-20 300 C180 210 250 355 430 275 S710 195 930 255" fill="none" stroke="currentColor" opacity=".16" stroke-width="28"/><text x="55" y="58" class="map-label">Qırmızı Qəsəbə · схема без платного картографического API</text>'+pts.map(p=>{const q=pos(p);return '<g class="map-point"><circle cx="'+q.x+'" cy="'+q.y+'" r="'+(p.demo?8:11)+'"/><text x="'+(q.x+15)+'" y="'+(q.y+5)+'">'+E(p.title)+'</text></g>'}).join('')+'</svg>';
  };

  H.pages['red-village']=()=>H.head('RED VILLAGE DIGITAL TWIN','Красная Слобода','Места, временные слои и связанные записи в одной базе. Карта схематическая: непроверенные координаты не выдаются за точные.')+
    '<section class="map-card">'+H.mapSvg()+'</section><section class="time-machine"><div><div class="kicker">МАШИНА ВРЕМЕНИ</div><h2 id="timeTitle">1750 → сегодня</h2><p class="muted">Передвигайте ползунок: показываются только записи, которые уже имеют временную привязку.</p></div><input id="yearRange" type="range" min="1750" max="2026" value="2026"><strong id="yearValue">2026</strong></section>'+
    '<section class="records-grid" id="placeGrid">'+D.places.map(H.placeCard).join('')+'</section>'+
    '<section class="section-block"><div class="section-title"><div><div class="kicker">ХРОНОЛОГИЯ</div><h2>Подтверждённые и рабочие записи</h2></div></div><div class="timeline">'+D.timeline.map(t=>'<article><time>'+E(t.label)+'</time><div><h3>'+E(t.title)+'</h3><p>'+E(t.text)+'</p>'+B(t.status)+S(t.sources)+'</div></article>').join('')+'</div></section>';

  H.archiveCard=x=>'<article class="record-card" data-kind="'+E(x.subtype)+'" data-search="'+E(H.recordText(x))+'"><div class="record-top"><span class="type">'+E(x.subtype)+'</span>'+B(x.status)+'</div><h3>'+E(x.title)+'</h3><p>'+E(x.summary)+'</p><div class="meta">'+E(x.period||'')+' · '+E(x.place||'')+'</div><div class="rights">Права: '+E(x.rights||'уточняются')+'</div>'+(x.private?'<div class="privacy-chip">🔒 содержимое скрыто</div>':'')+'</article>';
  H.pages.archive=()=>H.head('GLOBAL ARCHIVE','Архив','Фотографии, документы, видео и аудио с правами, уровнями доступа и статусом проверки.','<button class="btn secondary" id="exportArchive">Экспорт JSON</button>')+
    '<div class="toolbar"><input id="archiveFilter" class="field" placeholder="Поиск по архиву"><select id="archiveKind" class="field"><option value="">Все типы</option><option>Фото</option><option>Документ</option><option>Видео</option><option>Аудио</option></select></div><section class="records-grid" id="archiveGrid">'+D.archive.map(H.archiveCard).join('')+'</section><div class="notice"><strong>Приватность:</strong> содержимое приватных семейных документов в публичной версии не выводится. Показывается только паспорт записи.</div>';

  H.pages.families=()=>H.head('HERITAGE GRAPH','Семьи и люди','Связи фамилий, людей, домов, документов и мест. Демо-записи не являются реальными родословными.')+
    '<div class="graph-chain"><span>человек</span><b>→</b><span>семья</span><b>→</b><span>дом</span><b>→</b><span>место</span><b>→</b><span>документ</span><b>→</b><span>память</span></div>'+
    '<section class="section-block"><div class="section-title"><div><div class="kicker">ФАМИЛИИ</div><h2>Реестр</h2></div></div><div class="records-grid">'+D.families.map(f=>'<article class="record-card"><div class="record-top"><span class="type">Фамилия</span>'+B(f.status)+'</div><h3>'+E(f.title)+'</h3><p>'+E(f.summary)+'</p><div class="chips">'+f.spellings.map(s=>'<span>'+E(s)+'</span>').join('')+'</div><div class="meta">'+f.geography.map(E).join(' · ')+'</div></article>').join('')+'</div></section>'+
    '<section class="section-block"><div class="section-title"><div><div class="kicker">ЛЮДИ</div><h2>Карточки персон</h2></div><p>Живущие люди обезличиваются без явного согласия.</p></div><div class="records-grid">'+D.people.map(p=>'<article class="record-card"><div class="record-top"><span class="type">Человек</span>'+B(p.status)+'</div><h3>'+E(p.title)+'</h3><p>'+E(p.summary)+'</p><div class="meta">'+E(p.years||'')+'</div>'+(p.private?'<div class="privacy-chip">🔒 ограниченный доступ</div>':'')+'</article>').join('')+'</div></section>';

  H.pages.cemetery=()=>H.head('MEMORY REGISTER','Кладбище и память','Секции, захоронения, эпитафии, переводы и семейные связи. Текущие записи — демонстрационные.')+
    '<section class="cemetery-sections">'+D.cemeterySections.map(s=>'<article><strong>'+E(s.title)+'</strong><span>'+E(s.count)+' записей</span><small>'+E(s.note)+'</small>'+B(s.status)+'</article>').join('')+'</section>'+
    '<section class="records-grid">'+D.burials.map(b=>'<article class="record-card"><div class="record-top"><span class="type">Захоронение</span>'+B(b.status)+'</div><h3>'+E(b.title)+'</h3><div class="meta">'+E(b.years)+'</div><p><strong>Эпитафия:</strong> '+E(b.transcription)+'</p><p><strong>Перевод:</strong> '+E(b.translation)+'</p></article>').join('')+'</section><div class="notice">Рабочий принцип: фотография надгробия → транскрипция → перевод → идентификация человека → связь с семьёй и источником.</div>';

  H.wordCard=w=>{const src=H.source(w.source);return '<article class="word-card" data-dialect="'+E(w.dialect)+'" data-search="'+E(H.norm([w.lemma,...w.ru].join(' ')))+'"><div class="word-head"><span>'+E(w.pos)+'</span>'+B(w.status)+'</div><h3>'+E(w.lemma)+'</h3><p class="translation">'+E(w.ru.join(', '))+'</p>'+(w.example?'<blockquote>'+E(w.example)+'</blockquote>':'')+'<div class="word-source">'+E(src?src.title:w.source)+'<br><small>'+E(w.locator||'')+'</small></div></article>'};
  H.pages.juhuri=()=>H.head('JUHURI LANGUAGE LAB','Язык джуури','Поиск только по локальному проверенному корпусу. Система не придумывает переводов, которых нет в источниках.')+
    '<div class="toolbar"><input id="juhuriSearch" class="field big" placeholder="Слово на русском или джуури"><select id="dialectFilter" class="field"><option value="">Все диалекты</option><option value="guba">Губинский</option><option value="derbent">Дербентский</option><option value="kaitag">Кайтагский</option></select></div><div id="juhuriCount" class="result-count"></div><section class="word-grid" id="juhuriGrid">'+D.juhuri.map(H.wordCard).join('')+'</section><section class="section-block"><div class="section-title"><div><div class="kicker">БИБЛИОГРАФИЯ</div><h2>Источники языка</h2></div></div>'+S(D.sources.filter(s=>s.id!=='azt-ru'&&s.id!=='azt-en'&&s.id!=='osm').map(s=>s.id))+'</section>';

  H.quizIndex=0;
  H.pages.learn=()=>{const w=D.juhuri[H.quizIndex%D.juhuri.length],opts=[w,...D.juhuri.filter(x=>x.id!==w.id).slice(0,3)].sort((a,b)=>a.id.localeCompare(b.id));return H.head('УЧЕБНЫЙ РЕЖИМ','Учить джуури','Карточки и мини-тесты строятся только на словах из проверенного корпуса.')+'<section class="lesson-card"><div class="kicker">КАРТОЧКА '+(H.quizIndex%D.juhuri.length+1)+' ИЗ '+D.juhuri.length+'</div><h2>'+E(w.lemma)+'</h2><p id="lessonTranslation">—</p><div class="lesson-actions"><button id="revealWord" class="btn secondary">Показать перевод</button><button id="nextWord" class="btn primary">Дальше</button></div></section><section class="quiz"><h2>Что означает «'+E(w.lemma)+'»?</h2><div class="quiz-options">'+opts.map(o=>'<button data-answer="'+E(o.id)+'">'+E(o.ru[0])+'</button>').join('')+'</div><div id="quizFeedback"></div></section><section class="panel"><div class="kicker">ИСТОЧНИК КАРТОЧКИ</div><h3>'+E(H.source(w.source)?.title||w.source)+'</h3><p class="muted">'+E(w.locator||'')+'</p></section>'};
})();