(()=>{"use strict";
const STORE_KEY="qirmizi-master-store-v2";
const LEGACY_KEY="qirmizi-master-store-v1";
const DB_NAME="qirmizi-media-v1";

function defaults(){return{version:2,records:{},streets:{},materials:{},routes:[],contributions:[],settings:{lang:"ru"},audit:[],updatedAt:new Date().toISOString()}}
function load(){
  let obj=null;
  try{obj=JSON.parse(localStorage.getItem(STORE_KEY)||"null")}catch{}
  if(!obj){try{obj=JSON.parse(localStorage.getItem(LEGACY_KEY)||"null")}catch{}}
  const s=Object.assign(defaults(),obj||{});
  s.records=s.records||{};s.streets=s.streets||{};s.materials=s.materials||{};s.routes=s.routes||[];s.contributions=s.contributions||[];s.audit=s.audit||[];
  return s;
}
function save(s,action="update",target="project"){
  s.updatedAt=new Date().toISOString();
  s.audit=[...(s.audit||[]),{id:"AUD-"+crypto.randomUUID(),at:s.updatedAt,action,target}].slice(-5000);
  localStorage.setItem(STORE_KEY,JSON.stringify(s));
  return s;
}
function materialId(){return "MAT-"+crypto.randomUUID()}
function sha256(file){return file.arrayBuffer().then(buf=>crypto.subtle.digest("SHA-256",buf)).then(hash=>[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join(""))}
function imageDHash(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const cv=document.createElement("canvas");cv.width=9;cv.height=8;const x=cv.getContext("2d",{willReadFrequently:true});x.drawImage(img,0,0,9,8);const d=x.getImageData(0,0,9,8).data,bits=[];for(let y=0;y<8;y++)for(let xx=0;xx<8;xx++){const i=(y*9+xx)*4,j=i+4,g1=d[i]*.299+d[i+1]*.587+d[i+2]*.114,g2=d[j]*.299+d[j+1]*.587+d[j+2]*.114;bits.push(g1>g2?1:0)}let hex="";for(let i=0;i<64;i+=4)hex+=parseInt(bits.slice(i,i+4).join(""),2).toString(16);URL.revokeObjectURL(url);resolve(hex)}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Image decode failed"))};img.src=url})}
function hammingHex(a,b){if(!a||!b||a.length!==b.length)return Infinity;let n=0;for(let i=0;i<a.length;i++){let x=parseInt(a[i],16)^parseInt(b[i],16);while(x){n+=x&1;x>>=1}}return n}
async function readExif(file){const out={};if(!/jpe?g/i.test(file.type||file.name))return out;const buf=await file.arrayBuffer(),v=new DataView(buf);if(v.byteLength<4||v.getUint16(0)!==0xffd8)return out;let p=2;while(p+4<v.byteLength){if(v.getUint8(p)!==0xff){p++;continue}const marker=v.getUint8(p+1),len=v.getUint16(p+2);if(marker===0xe1&&p+4+len<=v.byteLength){const s=String.fromCharCode(...new Uint8Array(buf,p+4,6));if(s==="Exif\u0000\u0000"){const base=p+10,little=v.getUint16(base)===0x4949,u16=o=>v.getUint16(base+o,little),u32=o=>v.getUint32(base+o,little),i32=o=>v.getInt32(base+o,little),rat=o=>{const den=u32(o+4);return den?u32(o)/den:0};if(u16(2)!==42)return out;const readAscii=(off,count)=>{let st="";const start=count<=4?off: u32(off);const abs=base+start;for(let i=0;i<count&&abs+i<v.byteLength;i++){const ch=v.getUint8(abs+i);if(!ch)break;st+=String.fromCharCode(ch)}return st};const find=(ifdOff,tag)=>{if(!ifdOff||base+ifdOff+2>v.byteLength)return null;const n=u16(ifdOff);for(let i=0;i<n;i++){const e=ifdOff+2+i*12;if(u16(e)===tag)return e}return null};const valLong=e=>e?u32(e+8):0;const valAscii=e=>{if(!e)return"";return readAscii(e+8,u32(e+4))};const ifd0=u32(4),gpsPtr=valLong(find(ifd0,0x8825)),exifPtr=valLong(find(ifd0,0x8769));if(gpsPtr){const latRef=valAscii(find(gpsPtr,1)),lonRef=valAscii(find(gpsPtr,3));const readRats=e=>{if(!e)return null;const count=u32(e+4),off=u32(e+8),a=[];for(let i=0;i<count;i++)a.push(rat(off+i*8));return a};const la=readRats(find(gpsPtr,2)),lo=readRats(find(gpsPtr,4));if(la?.length>=3&&lo?.length>=3){let lat=la[0]+la[1]/60+la[2]/3600,lon=lo[0]+lo[1]/60+lo[2]/3600;if(latRef==="S")lat=-lat;if(lonRef==="W")lon=-lon;out.latitude=lat;out.longitude=lon}const de=find(gpsPtr,17);if(de){const off=u32(de+8);out.direction=rat(off)}}if(exifPtr){const dte=find(exifPtr,0x9003);if(dte)out.dateTimeOriginal=valAscii(dte)}return out}}p+=2+len}return out}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains("files"))db.createObjectStore("files",{keyPath:"id"});if(!db.objectStoreNames.contains("queue"))db.createObjectStore("queue",{keyPath:"id"})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbPut(storeName,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,"readwrite");tx.objectStore(storeName).put(value);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error)})}
async function dbGet(storeName,id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(storeName).objectStore(storeName).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function dbAll(storeName){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(storeName).objectStore(storeName).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function dbDelete(storeName,id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,"readwrite");tx.objectStore(storeName).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function safeUrl(u){try{const x=new URL(u,location.href);return["http:","https:","data:","blob:"].includes(x.protocol)?x.href:""}catch{return""}}
function download(name,text,type="application/json"){const a=document.createElement("a"),b=new Blob([text],{type});a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function center(f){const ring=f?.geometry?.coordinates?.[0]||[];if(!ring.length)return[48.5106,41.3736];const p=ring.length>1?ring.slice(0,-1):ring,s=p.reduce((a,x)=>[a[0]+x[0],a[1]+x[1]],[0,0]);return[s[0]/p.length,s[1]/p.length]}
function dist(a,b){const R=6371000,p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,dp=(b[1]-a[1])*Math.PI/180,dl=(b[0]-a[0])*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function label(f,s){const p=f?.properties||{},r=s.records?.[p.qqId];return r?.title||p.nameRu||p.name||[p.street,p.houseNumber].filter(Boolean).join(" ")||p.qqId||"Объект"}
function issues(f,s){const p=f.properties||{},r=s.records?.[p.qqId],a=[];if(!p.street&&!p.houseNumber)a.push("Нет адреса OSM");if(p.heightEstimated)a.push("Высота оценочная");if(!r?.media?.some(m=>m.type==="photo"))a.push("Нужна фотография");if(!r?.year)a.push("Не установлен период");if(r&&!r.sources?.length)a.push("Нужен источник");if(r?.issues?.length)a.push(...r.issues.map(x=>x.text||"Проверить запись"));return a}
function completeness(f,s){const r=s.records?.[f.properties.qqId];if(!r)return 0;let n=0;if(r.description)n+=15;if(r.year)n+=10;if(r.sources?.length)n+=20;if(r.media?.some(m=>m.type==="photo"))n+=20;if(r.media?.some(m=>m.type==="video"))n+=5;if(r.panoramaUrl)n+=10;if(r.modelUrl)n+=10;if(r.audioUrl)n+=5;if(r.verification==="verified")n+=5;return Math.min(100,n)}
function buildStreetIndex(data,s){const streets={};for(const f of data?.buildings?.features||[]){const name=f.properties.street||"Без улицы";(streets[name]??=[]).push(f.properties.qqId)}for(const [name,ids] of Object.entries(streets)){s.streets[name]={...(s.streets[name]||{}),name,houseIds:ids,updatedAt:new Date().toISOString()}}return s}
function kml(data,s){const pm=(x)=>Number(x).toFixed(7);const placemarks=(data?.buildings?.features||[]).map(f=>{const c=center(f),r=s.records?.[f.properties.qqId];return `<Placemark><name>${esc(label(f,s))}</name><description><![CDATA[${esc(r?.description||"")}]]></description><ExtendedData><Data name="qqId"><value>${esc(f.properties.qqId)}</value></Data><Data name="progress"><value>${completeness(f,s)}</value></Data></ExtendedData><Point><coordinates>${pm(c[0])},${pm(c[1])},0</coordinates></Point></Placemark>`}).join("");return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Qirmizi Qesebe</name>${placemarks}</Document></kml>`}
function iiifManifest(house,data,s){const f=(data?.buildings?.features||[]).find(x=>x.properties.qqId===house),r=s.records?.[house];if(!f)return null;const imgs=(r?.media||[]).filter(m=>m.type==="photo"&&/^https?:/.test(m.url||""));return{"@context":"http://iiif.io/api/presentation/3/context.json",id:location.origin+location.pathname.replace(/[^/]+$/,"")+"iiif/"+encodeURIComponent(house)+".json",type:"Manifest",label:{ru:[label(f,s)]},metadata:[{label:{ru:["QQ-ID"]},value:{none:[house]}},{label:{ru:["Источник"]},value:{ru:[(r?.sources||[]).map(x=>x.label||x.url).filter(Boolean).join("; ")||"Не указан"]}}],items:imgs.map((m,i)=>({id:`urn:qq:${house}:canvas:${i+1}`,type:"Canvas",height:1000,width:1500,items:[{id:`urn:qq:${house}:page:${i+1}`,type:"AnnotationPage",items:[{id:`urn:qq:${house}:annotation:${i+1}`,type:"Annotation",motivation:"painting",body:{id:m.url,type:"Image",format:"image/jpeg"},target:`urn:qq:${house}:canvas:${i+1}`}]}]}))}
window.QQCore={STORE_KEY,DB_NAME,load,save,materialId,sha256,imageDHash,hammingHex,readExif,dbPut,dbGet,dbAll,dbDelete,esc,safeUrl,download,center,dist,label,issues,completeness,buildStreetIndex,kml,iiifManifest};
})();